CC = gcc
FLAGS = -std=c99 -Wall
# Add all source files included in your project here:
SRC = LUfact.c LUtest.c
# Specify the name of your executable here:
EXEC = LUtest

${EXEC}: ${SRC}
	${CC} ${FLAGS} ${SRC} -o ${EXEC} -lm

# Runs your compiled file with the incorporated LU factorization library.
run: ${EXEC}
	./${EXEC}

# Cleans up the executable generated by this Makefile.
clean:
	rm -f ${EXEC}
